#!/bin/bash

# set -e: don't tolerate non-zero exit status for any command
# set -u: only allow referencing of variables if they were previously defined
# set -o pipefail: prevent errors in a pipeline from being masked
set -euo pipefail

TAG=${TAG:-4.0.5-node-yarn-wkhtmltopdf-ffmpeg}

NAME=ghcr.io/denkungsart/ci-ruby:"$TAG"

# docker buildx create --use --platform=linux/arm64,linux/amd64 --name multi-platform-builder
mkdir -p logs
docker buildx build \
  --platform linux/amd64 \
  --output type=docker \
  --tag "$NAME" . &> logs/"$(date +%F)"-"$(date +%T)".log
