#!/bin/bash
set -xeo pipefail

# Download and install nvm:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

# in lieu of restarting the shell
export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
. "$NVM_DIR/nvm.sh"

# Download and install Node.js:
nvm install 24

# Make node/npm available to subsequent Docker layers
NODE_BIN_DIR="$NVM_DIR/versions/node/$(nvm version)/bin"
install -d /usr/local/bin
ln -sf "$NODE_BIN_DIR/node" /usr/local/bin/node
ln -sf "$NODE_BIN_DIR/npm" /usr/local/bin/npm
ln -sf "$NODE_BIN_DIR/npx" /usr/local/bin/npx
ln -sf "$NODE_BIN_DIR/corepack" /usr/local/bin/corepack

node -v
npm -v
