#!/bin/bash
set -xeo pipefail

apt-get update
apt-get install -y --no-install-recommends \
  postgresql-client \
  libvips42 \
  jq \
  pdftk \
  ghostscript \
  qpdf \
  poppler-utils
apt-get clean
rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*
