#!/bin/bash
set -xeo pipefail

NODE_MAJOR=20

# prerequisites for fetching GPG key and using HTTPS apt sources
apt-get update
apt-get install -y --no-install-recommends curl ca-certificates gnupg

# ref https://github.com/nodesource/distributions?tab=readme-ov-file#installation-instructions
mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
apt-get update

apt-get install -y --no-install-recommends nodejs
