#!/bin/bash
set -xeo pipefail

apt-get update
apt-get install -y --no-install-recommends \
  xfonts-75dpi \
  xfonts-base \
  fontconfig \
  fonts-dejavu \
  fonts-liberation

# ref https://github.com/wkhtmltopdf/packaging/releases
WKHTMLTOPDF_RELEASE_VERSION="0.12.6.1-3"
WKHTMLTOPDF_BINARY="wkhtmltox_${WKHTMLTOPDF_RELEASE_VERSION}.bookworm_${TARGETPLATFORM#*/}.deb"

wget "https://github.com/wkhtmltopdf/packaging/releases/download/${WKHTMLTOPDF_RELEASE_VERSION}/${WKHTMLTOPDF_BINARY}"
dpkg -i "${WKHTMLTOPDF_BINARY}"
rm "${WKHTMLTOPDF_BINARY}"
apt-get clean
rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*
